<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'5YGl5bq35aSq5bmz5LmL6YCJ');
$cfg_Cs[2]=array(1,1,1,'5qmE5qaE5rK5');
$cfg_Cs[3]=array(1,1,1,'5oSP5aSn5Yip6Z2i');
$cfg_Cs[4]=array(1,1,1,'5YW25LuW5Lqn5ZOB');
$cfg_Cs[5]=array(0,1,1,'5ZOB54mM5paH5YyW');
$cfg_Cs[6]=array(0,1,1,'5Lyv54i15Zyw5Lit5rW3');
$cfg_Cs[7]=array(6,1,1,'6ZuG5Zui5Y6G5Y+y');
$cfg_Cs[8]=array(6,1,1,'5LyB5Lia5Lu35YC8');
$cfg_Cs[9]=array(6,1,1,'6I2j6KqJ6LWE6LSo');
$cfg_Cs[10]=array(6,1,1,'5Yqo5oCB6LWE6K6v');
$cfg_Cs[11]=array(0,1,1,'6JCl5YW755Sf5rS76aaG');
$cfg_Cs[12]=array(0,1,1,'6IGU57O75oiR5Lus');
?>