<li>
          <div class="gly_left fl"><a href="[field:arcurl/]" title="[field:title/]"><img src="[field:picname/]" width="636" height="287" alt="[field:title/]" /></a></div>
          <div class="gly_right fl pl40"> <a href="[field:arcurl/]" title="[field:title/]">
            <p class="baiszt26">[field:title/]</p>
            <p class="baiszt12 mt30">[field:description/]</p>
            </a>
            <p class="baiszt pt95">[field:pubdate function="MyDate('Y-m-d',@me)"/]<a href="[field:arcurl/]" class="ml185">更多+</a></p>
          </div>
        </li>