<?php
$z[0]=Array("field","",111,130);
$z[0][4]['name']="title";
$z[1]=Array("global","",131,157);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",198,220);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",260,311);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",698,733);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",1894,1913);
$z[5][4]['name']="title";
$z[6]=Array("field","",2065,2083);
$z[6][4]['name']="body";
$z[7]=Array("arclist","\r\n          <li><a href=\"[field:arcurl/]\"> <img src=\"[field:picname/]\" width=\"94\" height=\"192\" /></a><span>[field:title/]</span></li>\r\n          ",2444,2649);
$z[7][4]['titlelen']="42";
$z[7][4]['row']="8";
$z[7][4]['typeid']="3";
$z[8]=Array("include","",2818,2855);
$z[8][4]['filename']="footer.htm";

?>