<?php
$z[0]=Array("field","",177,196);
$z[0][4]['name']="title";
$z[1]=Array("global","",197,223);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",264,293);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",333,391);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",778,813);
$z[4][4]['filename']="head.htm";
$z[5]=Array("include","",2695,2732);
$z[5][4]['filename']="footer.htm";

?>