<div class="nutrition_nr fl">
      <div class="nutrition_nrup baiszt22 xianup">
        <p class="pt10"> [field:title/]</p>
      </div>
      <div class="nutrition_nrmiddle xianmiddle chufa">
        <div class="zhezao"> <img src="/skin/images/zhezao.png"></div>
        <a href="[field:arcurl/]"> <img class="" src="[field:picname/]" alt="[field:title/]" /></a> </div>
      <div class="nutrition_nrdown baiszt18 xiandown"> [field:description function='cn_substr(@me,70)'/]……</div>
    </div>