<?php
$z[0]=Array("channelartlist","\r\n        <li class=\"fl nav2\"><a href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}</a>\r\n          <dl class=\"nav_xiasy2\">\r\n            {dede:channel type='son' noself='yes'}\r\n            <dd class=\"fl\"><a href=\"[field:typelink/]\">[field:typename/]</a></dd>\r\n            {/dede:channel}\r\n          </dl>\r\n        </li>\r\n        ",508,907);
$z[0][4]['typeid']="top";

?>