<?php
$z[0]=Array("global","",543,569);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",613,643);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",680,707);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("include","",1423,1458);
$z[3][4]['filename']="head.htm";
$z[4]=Array("myad","",2491,2513);
$z[4][4]['name']="tb";
$z[5]=Array("type","<a href=\"[field:typelink/]\"> <img src=\"/skin/images/index_pic1.png\"></a>",2789,2897);
$z[5][4]['typeid']="6";
$z[6]=Array("type","<a href=\"[field:typelink/]\">\r\n            <p> 我们摘取最新鲜的橄榄果并在最短的时间内完成所</p>\r\n            <p> 有的加工程序。生产中我们采用机械冷榨的</p>\r\n            <p> 方法榨取油橄榄果汁并过滤，不经任</p>\r\n            <p> 何化学处理，不含任何...</p>\r\n            </a>",3459,3833);
$z[6][4]['typeid']="6";
$z[7]=Array("type"," <a href=\"[field:typelink/]\"> <img src=\"/skin/images/index_pic2.png\"></a>",4024,4133);
$z[7][4]['typeid']="8";
$z[8]=Array("type","<a href=\"[field:typelink/]\">\r\n            <p> 一个多世纪以來 我们追求卓越自1896年以來，直</p>\r\n            <p> 到今天，我们的目标是通过我们的产品将“地</p>\r\n            <p> 中海式的生活和质量”理念传播于世</p>\r\n            <p> 界各地的消费者和企业。</p>\r\n            </a> ",4695,5069);
$z[8][4]['typeid']="8";
$z[9]=Array("type"," <a href=\"[field:typelink/]\"> <img src=\"/skin/images/index_pic3.png\"></a>",5259,5369);
$z[9][4]['typeid']="11";
$z[10]=Array("type"," <a href=\"[field:typelink/]\" title=\"\">\r\n            <p> 橄榄油能促进皮肤的新陈代谢，具有养生的</p>\r\n            <p> 功效。将橄榄油轻点在痘子上，能使闭</p>\r\n            <p> 塞的毛孔张开，令其中的皮脂自然</p>\r\n            </a> ",5934,6247);
$z[10][4]['typeid']="11";
$z[11]=Array("include","",6340,6377);
$z[11][4]['filename']="footer.htm";

?>