<?php
$z[0]=Array("field","",111,130);
$z[0][4]['name']="title";
$z[1]=Array("global","",131,157);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",198,227);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",267,325);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",714,749);
$z[4][4]['filename']="head.htm";
$z[5]=Array("myad","",1029,1051);
$z[5][4]['name']="jt";
$z[6]=Array("include","",6851,6888);
$z[6][4]['filename']="footer.htm";

?>