<?php
$z[0]=Array("field","",177,196);
$z[0][4]['name']="title";
$z[1]=Array("global","",197,223);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",264,293);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",333,391);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",828,863);
$z[4][4]['filename']="head.htm";
$z[5]=Array("list","\r\n    <div class=\"nutrition_nr fl\">\r\n      <div class=\"nutrition_nrup baiszt22 xianup\">\r\n        <p class=\"pt10\"> [field:title/]</p>\r\n      </div>\r\n      <div class=\"nutrition_nrmiddle xianmiddle chufa\">\r\n        <div class=\"zhezao\"> <img src=\"/skin/images/zhezao.png\"></div>\r\n        <a href=\"[field:arcurl/]\"> <img class=\"\" src=\"[field:picname/]\" alt=\"[field:title/]\" /></a> </div>\r\n      <div class=\"nutrition_nrdown baiszt18 xiandown\"> [field:description function='cn_substr(@me,70)'/]……</div>\r\n    </div>\r\n    ",1016,1571);
$z[5][4]['pagesize']="6";
$z[6]=Array("include","",1613,1650);
$z[6][4]['filename']="footer.htm";

?>