<?php
$z[0]=Array("field","",111,130);
$z[0][4]['name']="title";
$z[1]=Array("global","",131,157);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",198,227);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",267,325);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1415,1450);
$z[4][4]['filename']="head.htm";
$z[5]=Array("list","\r\n      <li class=\"pr50 \"><a href=\"[field:arcurl/]\"> <img src=\"[field:picname/]\"></a>\r\n        <div class=\"italychen2_hdx\">[field:title/]</div>\r\n        <div class=\"italychen2_fixTxt\"> [field:description/]</div>\r\n      </li>\r\n      ",2669,2937);
$z[5][4]['pagesize']="4";

?>